#!/bin/bash
options=("${@:1:$(($# - 1))}") # Everything in "$@" except the last argument
target="${!#}"                 # The last argument from "$@"
remote="${target%:*}"
path="${target##*:}"
exec ssh -t "${options[@]}" "${remote}" "cd ${path}; exec \$SHELL -l"
